<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Customer_request_registration_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get customer_request_registration by id
     */
    function get_customer_request_registration($id)
    {
        return $this->db->get_where('customer_request_registration',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all customer_request_registration
     */
    function get_all_customer_request_registration()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('customer_request_registration')->result_array();
    }
        
    /*
     * function to add new customer_request_registration
     */
    function add_customer_request_registration($params)
    {
        $this->db->insert('customer_request_registration',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update customer_request_registration
     */
    function update_customer_request_registration($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('customer_request_registration',$params);
    }
    
    /*
     * function to delete customer_request_registration
     */
    function delete_customer_request_registration($id)
    {
        return $this->db->delete('customer_request_registration',array('id'=>$id));
    }
    function updateItems($table,$params,$where)
    {
        return $this->db->update($table,$params,$where);
    }
    public function getTableAllDataOrder($table,$column,$order)
    {
        $this->db->select("*")->from($table)->order_by($column,$order);
        $query = $this->db->get();
        if($query->num_rows() > 0)
        {
            return $query->result();
        }
        else
        {
            return array();
        }
    }
    public function getTableRowDataOrder($table,$where,$column,$order)
    {
        $this->db->where($where);
        $this->db->order_by($column, $order);
        return $this->db->get($table)->result_array();
    }
}
