<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Sql_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    public function getTableAllDataOrder($table,$column,$order)
    {
        $this->db->select("*")->from($table)->order_by($column,$order);
        $query = $this->db->get();
        if($query->num_rows() > 0)
        {
            return $query->result();
        }
        else
        {
            return array();
        }
    }
    public function getTableRowDataOrder($table,$where,$column,$order)
    {
        $this->db->select("*")->from($table)->where($where)->order_by($column,$order);
        $query = $this->db->get();
        if($query->num_rows() > 0)
        {
            return $query->result();
        }
        else
        {
            return array();
        }
    }
    function storeItems($table,$params)
    {
        $this->db->insert($table,$params);
        return $this->db->insert_id();
    }
    function updateItems($table,$params,$where)
    {
        $this->db->where($where);
        return $this->db->update($table,$params);
    }
    function deleteItemsById($table,$where)
    {
        return $this->db->delete($table,$where);
    }
}
